version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-broker1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  #kafka-broker2:
   # image: wurstmeister/kafka
    #ports:
     # - "9092:9092"
    #environment:
     # KAFKA_BROKER_ID: 2
      #KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

#  kafka-broker3:
 #   image: wurstmeister/kafka
  #  ports:
   #   - "9093:9092"
    #environment:
     # KAFKA_BROKER_ID: 3
      #KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'